#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon May 09 11:15:07 CEST 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_gen_check_behav -key {Behavioral:sim_1:Functional:tb_gen_check} -tclbatch tb_gen_check.tcl -view /home/simbu448/Documents/vivado/aurora_64b66b-vhdl-sim/aurora_4_lanes/tb_verilog_vhdl/tb_gen_check_behav.wcfg -log simulate.log"
xsim tb_gen_check_behav -key {Behavioral:sim_1:Functional:tb_gen_check} -tclbatch tb_gen_check.tcl -view /home/simbu448/Documents/vivado/aurora_64b66b-vhdl-sim/aurora_4_lanes/tb_verilog_vhdl/tb_gen_check_behav.wcfg -log simulate.log

