webtalk_init -webtalk_dir /home/simbu448/Documents/vivado/aurora_64b66b-vhdl-sim/aurora_1_lanes/tb_verilog_vhdl/tb_verilog_vhdl.sim/sim_1/behav/xsim/xsim.dir/tb_gen_check_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed May 11 08:34:15 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211887302_1777494980_210602001_508" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "eca886e2-54fb-4429-860f-b27211968d93" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9e6427a29ffd4bcb9d6415a555c2e981" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "17" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "CentOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "CentOS Linux release 7.9.2009 (Core)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3219.958 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "25.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "15" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "78 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "9 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "108" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "13" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "2.57_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "397272_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3642640500 -regid "211887302_1777494980_210602001_508" -xml /home/simbu448/Documents/vivado/aurora_64b66b-vhdl-sim/aurora_1_lanes/tb_verilog_vhdl/tb_verilog_vhdl.sim/sim_1/behav/xsim/xsim.dir/tb_gen_check_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/simbu448/Documents/vivado/aurora_64b66b-vhdl-sim/aurora_1_lanes/tb_verilog_vhdl/tb_verilog_vhdl.sim/sim_1/behav/xsim/xsim.dir/tb_gen_check_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/simbu448/Documents/vivado/aurora_64b66b-vhdl-sim/aurora_1_lanes/tb_verilog_vhdl/tb_verilog_vhdl.sim/sim_1/behav/xsim/xsim.dir/tb_gen_check_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
