webtalk_init -webtalk_dir /home/simbu448/Documents/vivado/aurora_64b66b-vhdl-sim/aurora_1_lanes/tb_verilog_vhdl/tb_verilog_vhdl.sim/sim_1/behav/xsim/xsim.dir/tb_gen_check_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon May  9 11:24:08 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211887302_1777494980_210602001_508" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "eca886e2-54fb-4429-860f-b27211968d93" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6186b38c0c6443c7a58ec5f1da1bbd23" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "64" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "CentOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "CentOS Linux release 7.9.2009 (Core)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3247.772 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "25.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "3 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "133588_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3301342331 -regid "211887302_1777494980_210602001_508" -xml /home/simbu448/Documents/vivado/aurora_64b66b-vhdl-sim/aurora_1_lanes/tb_verilog_vhdl/tb_verilog_vhdl.sim/sim_1/behav/xsim/xsim.dir/tb_gen_check_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/simbu448/Documents/vivado/aurora_64b66b-vhdl-sim/aurora_1_lanes/tb_verilog_vhdl/tb_verilog_vhdl.sim/sim_1/behav/xsim/xsim.dir/tb_gen_check_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/simbu448/Documents/vivado/aurora_64b66b-vhdl-sim/aurora_1_lanes/tb_verilog_vhdl/tb_verilog_vhdl.sim/sim_1/behav/xsim/xsim.dir/tb_gen_check_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
